### ISSUE TITLE
Interested in Contributing

### ISSUE THREAD

**Issue by VishnuSanal** [KochiFOSS/kochifoss.github.io#1]
As discussed today at the KochiFOSS event, I'd like to volunteer in building the website. Saw no open issues, hence creating this thread for volunteers to show interest!

**Comment by subins2000** [comment]
Initial set of tasks to work on
- [x] Make a simple hugo setup with current index.html and github actions to deploy it
- [x] Create a timeline in the homepage itself, clicking on an item should show the group picture and a brief explanation. https://kochifoss.org/meetups/2024-10 A bit of timeline design is there in PR #2 by @xenomech
- [ ] Create an about page

Website design inspirations:
* https://linuxdelhi.org
* https://news.ycombinator.com
